[package]
name = "ao3_epubinator"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.14.0"
derivative = "2.2.0"
lazy_static = "1.5.0"
regex = "1.12.2"
scraper = "0.24.0"
structopt = "0.3.26"
